name: Waka Readme

on:
  schedule:
    - cron: '15 15 * * 0'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: wirsnow/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          SHOW_LINES_OF_CODE: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: True
          SHOW_LANGUAGE: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_LOC_CHART: False
